export type QuestionType = "scale" | "choice" | "freetext"

export interface Question {
  id: string
  category: string
  text: string
  type: QuestionType
  options?: string[]
  scaleMin?: number
  scaleMax?: number
  scaleLabels?: { min: string; max: string }
  placeholder?: string
  // Conditional variants based on category score
  variants?: {
    low?: { text: string; placeholder?: string }  // Score < 6
    high?: { text: string; placeholder?: string } // Score >= 6
  }
}

export const assessmentQuestions: Question[] = [
  // Unternehmerisches Denken & Entscheidungslogik
  {
    id: "ut-1",
    category: "Unternehmerisches Denken",
    text: "Ich treffe unternehmerische Entscheidungen überwiegend aus Klarheit – nicht aus Druck.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "ut-2",
    category: "Unternehmerisches Denken",
    text: "Ich habe ein inneres Bild davon, wie mein Unternehmen in Zukunft aussehen soll, das mich motiviert.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "ut-3",
    category: "Unternehmerisches Denken",
    text: "Wenn Probleme auftreten, denke ich zuerst in Lösungen, nicht in Rechtfertigungen.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "ut-4",
    category: "Unternehmerisches Denken",
    text: "Ich erkenne früh, wann ich aus Gewohnheit statt aus Strategie handle.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "ut-6",
    category: "Unternehmerisches Denken",
    text: "Ich arbeite bewusst an meinem Unternehmen – nicht nur aus dem Tagesgeschäft heraus.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "ut-7",
    category: "Unternehmerisches Denken",
    text: "Ich kann Chancen erkennen, bevor sie offensichtlich sind.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "ut-8",
    category: "Unternehmerisches Denken",
    text: "Ich hinterfrage regelmäßig meine eigenen Denk- und Entscheidungsroutinen.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "ut-9",
    category: "Unternehmerisches Denken",
    text: "Wachstum fühlt sich für mich gestaltbar an – nicht bedrohlich.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "ut-10",
    category: "Unternehmerisches Denken",
    text: "Ich kenne meine unternehmerischen Prioritäten auch unter Stress.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "ut-11",
    category: "Unternehmerisches Denken",
    text: "Ich entscheide lieber klar als perfekt.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "ut-13",
    category: "Unternehmerisches Denken",
    text: "Zahlen unterstützen meine Entscheidungen – sie ersetzen sie nicht.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "ut-14",
    category: "Unternehmerisches Denken",
    text: "Ich sehe mein Unternehmen als System, nicht nur als Summe von Aufgaben.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "ut-text-1",
    category: "Unternehmerisches Denken",
    text: "Was ist momentan Ihre größte strategische Herausforderung?",
    type: "freetext",
    placeholder: "Beschreiben Sie Ihre aktuelle strategische Herausforderung...",
  },
  {
    id: "ut-text-2",
    category: "Unternehmerisches Denken",
    text: "Was hindert Sie daran, mehr am Unternehmen statt im Unternehmen zu arbeiten?",
    type: "freetext",
    placeholder: "z.B. Zeitmangel, fehlende Prozesse, Mitarbeiter nicht bereit...",
  },

  // Leadership, Wirkung & innere Haltung
  {
    id: "lf-1",
    category: "Leadership & Führung + Emotionen",
    text: "Ich bin mir bewusst, welchen emotionalen Zustand ich in meinem Team auslöse.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "lf-2",
    category: "Leadership & Führung + Emotionen",
    text: "Menschen spüren Klarheit, wenn ich Entscheidungen kommuniziere.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "lf-3",
    category: "Leadership & Führung + Emotionen",
    text: "Ich kann meine Rolle wechseln: vom Mitmacher zum Entscheider.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "lf-4",
    category: "Leadership & Führung + Emotionen",
    text: "Ich erkenne früh, wenn meine innere Haltung meine Führung beeinflusst.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "lf-5",
    category: "Leadership & Führung + Emotionen",
    text: "Mein Führungsverhalten ist auch unter Druck konsistent.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "lf-6",
    category: "Leadership & Führung + Emotionen",
    text: "Ich weiß, wann Kontrolle sinnvoll ist – und wann Vertrauen stärker wirkt.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "lf-7",
    category: "Leadership & Führung + Emotionen",
    text: "Mein Team orientiert sich an mir, nicht nur an Prozessen.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "lf-8",
    category: "Leadership & Führung + Emotionen",
    text: "Ich kann schwierige Gespräche führen, ohne innere Anspannung mitzunehmen.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "lf-9",
    category: "Leadership & Führung + Emotionen",
    text: "Ich bin mir meiner Wirkung bewusst – verbal und nonverbal.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "lf-10",
    category: "Leadership & Führung + Emotionen",
    text: "Ich handle als Führungskraft bewusst, nicht impulsiv.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "lf-11",
    category: "Leadership & Führung + Emotionen",
    text: "Ich entwickle andere Menschen gezielt weiter.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "lf-14",
    category: "Leadership & Führung + Emotionen",
    text: "Ich fühle mich innerlich stimmig in meiner Rolle als Unternehmer.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "lf-text-1",
    category: "Leadership & Führung + Emotionen",
    text: "Wie beschreiben Sie Ihren aktuellen Führungsstil?",
    type: "freetext",
    placeholder: "z.B. delegativ, partizipativ, direktiv, coaching-orientiert...",
    variants: {
      low: {
        text: "Was frustriert Sie am meisten bei Ihrer Mitarbeiterführung?",
        placeholder: "z.B. mangelnde Eigenverantwortung, fehlende Initiative, Kommunikationsprobleme..."
      },
      high: {
        text: "Wie entwickeln Sie Ihre Führungskompetenzen kontinuierlich weiter?",
        placeholder: "z.B. Coaching, Mentoring, Weiterbildungen, Peer-Austausch..."
      }
    }
  },
  {
    id: "lf-text-2",
    category: "Leadership & Führung + Emotionen",
    text: "Welchen Aspekt Ihrer Führung möchten Sie weiterentwickeln?",
    type: "freetext",
    placeholder: "z.B. Delegation, Feedback-Kultur, Mitarbeiterentwicklung, Entscheidungsfindung...",
    variants: {
      low: {
        text: "Warum delegieren Sie nicht mehr Verantwortung an Ihr Team?",
        placeholder: "z.B. Vertrauensmangel, fehlende Kompetenz im Team, schlechte Erfahrungen..."
      },
      high: {
        text: "Wie fördern Sie gezielt die Eigenverantwortung in Ihrem Team?",
        placeholder: "z.B. konkrete Methoden, Tools, Rituale zur Teamentwicklung..."
      }
    }
  },
  {
    id: "lf-text-3",
    category: "Leadership & Führung + Emotionen",
    text: "Was ist Ihre größte Herausforderung beim Aufbau einer starken Führungskultur?",
    type: "freetext",
    placeholder: "Beschreiben Sie konkrete Situationen oder Hindernisse...",
    variants: {
      low: {
        text: "Was würde sich ändern, wenn Ihr Team vollständig eigenverantwortlich arbeiten würde?",
        placeholder: "Beschreiben Sie den Impact auf Ihr Unternehmen und Ihre Rolle..."
      },
      high: {
        text: "Welche Führungsprinzipien haben Ihren größten Erfolg ermöglicht?",
        placeholder: "Beschreiben Sie konkrete Beispiele und deren Auswirkungen..."
      }
    }
  },

  // Vertrieb, Marktpsychologie & Wachstum
  {
    id: "vw-1",
    category: "Vertrieb & Wachstum",
    text: "Unser Vertrieb folgt einer klaren Logik – nicht nur Erfahrung.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "vw-2",
    category: "Vertrieb & Wachstum",
    text: "Ich verstehe, warum Kunden sich für uns entscheiden.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "vw-3",
    category: "Vertrieb & Wachstum",
    text: "Unsere Angebote erzeugen Klarheit, nicht Verwirrung.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "vw-4",
    category: "Vertrieb & Wachstum",
    text: "Wir verkaufen Nutzen, nicht nur Leistungen.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "vw-5",
    category: "Vertrieb & Wachstum",
    text: "Preisgespräche verlaufen bei uns überwiegend souverän.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "vw-6",
    category: "Vertrieb & Wachstum",
    text: "Unser Vertriebsprozess ist reproduzierbar.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "vw-7",
    category: "Vertrieb & Wachstum",
    text: "Entscheidungen im Vertrieb basieren auf Daten und Beobachtung.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "vw-8",
    category: "Vertrieb & Wachstum",
    text: "Wir sprechen gezielt die richtigen Kunden an.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "vw-9",
    category: "Vertrieb & Wachstum",
    text: "Unser Marktauftritt wirkt professionell und konsistent.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "vw-10",
    category: "Vertrieb & Wachstum",
    text: "Vertrieb fühlt sich steuerbar an – nicht zufällig.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "vw-12",
    category: "Vertrieb & Wachstum",
    text: "Wachstum ist bei uns strategisch vorbereitet.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "vw-13",
    category: "Vertrieb & Wachstum",
    text: "Wir erkennen früh, warum Deals scheitern oder gewinnen.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "vw-text-1",
    category: "Vertrieb & Wachstum",
    text: "Was ist Ihr größtes Hindernis beim Umsatzwachstum?",
    type: "freetext",
    placeholder: "z.B. zu wenig Leads, schlechte Conversion, hohe Kundenabwanderung...",
  },
  {
    id: "vw-text-2",
    category: "Vertrieb & Wachstum",
    text: "Warum verlieren Sie Kunden-Deals oder Aufträge?",
    type: "freetext",
    placeholder: "z.B. Preis zu hoch, fehlende Differenzierung, lange Reaktionszeiten...",
  },

  // Selbstmanagement, Emotionen & Resilienz
  {
    id: "sr-1",
    category: "Selbstmanagement & Resilienz",
    text: "Ich erkenne früh, in welchem mentalen Zustand ich mich befinde.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "sr-2",
    category: "Selbstmanagement & Resilienz",
    text: "Ich kann bewusst aus Stress in Klarheit wechseln.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "sr-3",
    category: "Selbstmanagement & Resilienz",
    text: "Ich handle unter Druck überlegt, nicht impulsiv.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "sr-4",
    category: "Selbstmanagement & Resilienz",
    text: "Ich weiß, welche Zustände meine Leistung verbessern.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "sr-7",
    category: "Selbstmanagement & Resilienz",
    text: "Rückschläge beeinträchtigen meine Handlungsfähigkeit nur kurzfristig.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "sr-8",
    category: "Selbstmanagement & Resilienz",
    text: "Ich bin mir meiner emotionalen Muster bewusst.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "sr-9",
    category: "Selbstmanagement & Resilienz",
    text: "Ich treffe Entscheidungen aus innerer Sicherheit.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "sr-10",
    category: "Selbstmanagement & Resilienz",
    text: "Ich kann Verantwortung tragen, ohne mich zu überlasten.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "sr-11",
    category: "Selbstmanagement & Resilienz",
    text: "Ich habe Rituale, die meine Klarheit unterstützen.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "sr-12",
    category: "Selbstmanagement & Resilienz",
    text: "Ich erlebe mein Unternehmertum als sinnstiftend.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "sr-13",
    category: "Selbstmanagement & Resilienz",
    text: "Ich fühle mich innerlich stabil – auch in unsicheren Phasen.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "sr-14",
    category: "Selbstmanagement & Resilienz",
    text: "Mein innerer Zustand unterstützt mein Wachstum als Unternehmer.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "sr-text-1",
    category: "Selbstmanagement & Resilienz",
    text: "Wann fühlen Sie sich am meisten überfordert oder gestresst?",
    type: "freetext",
    placeholder: "z.B. bei wichtigen Entscheidungen, in Konflikten, bei Zeitdruck...",
  },
  {
    id: "sr-text-2",
    category: "Selbstmanagement & Resilienz",
    text: "Was würden Sie tun, wenn Sie 10 Stunden pro Woche mehr Zeit hätten?",
    type: "freetext",
    placeholder: "z.B. strategische Planung, Kundenakquise, persönliche Weiterbildung...",
  },
  {
    id: "sr-text-3",
    category: "Selbstmanagement & Resilienz",
    text: "Was ist Ihr unternehmerisches Ziel in 90 Tagen?",
    type: "freetext",
    placeholder: "Beschreiben Sie Ihr konkretes 90-Tage-Ziel...",
  },

  // Finanzen & Controlling
  {
    id: "fc-1",
    category: "Finanzen & Controlling",
    text: "Wenn ich JETZT gefragt werde: Wie viel Geld ist aktuell verfügbar? – könnte ich die Zahl sofort nennen?",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "fc-2",
    category: "Finanzen & Controlling",
    text: "Ich schaue mindestens wöchentlich auf meine wichtigsten 3-5 Finanzkennzahlen.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "fc-3",
    category: "Finanzen & Controlling",
    text: "Ich plane mein Budget regelmäßig.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "fc-4",
    category: "Finanzen & Controlling",
    text: "Meine Preiskalkulation basiert auf fundierten Zahlen, nicht auf Bauchgefühl.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "fc-5",
    category: "Finanzen & Controlling",
    text: "Ich habe Rücklagen für Krisenzeiten oder unerwartete Ausgaben.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "fc-6",
    category: "Finanzen & Controlling",
    text: "Ich verstehe meine Gewinn- und Verlustrechnung und nutze sie aktiv.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "fc-7",
    category: "Finanzen & Controlling",
    text: "Ich treffe finanzielle Entscheidungen auf Basis von Kennzahlen.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "fc-8",
    category: "Finanzen & Controlling",
    text: "Mein Cashflow ist stabil und planbar.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "fc-text-1",
    category: "Finanzen & Controlling",
    text: "Was ist Ihre größte finanzielle Sorge im Unternehmen?",
    type: "freetext",
    placeholder: "z.B. schwankender Cashflow, zu geringe Marge, hohe Fixkosten...",
  },
  {
    id: "fc-text-3",
    category: "Finanzen & Controlling",
    text: "Wie oft schauen Sie auf Ihre wichtigsten Finanzkennzahlen?",
    type: "freetext",
    placeholder: "z.B. täglich, wöchentlich, monatlich, nie...",
  },

  // Marketing & Marke
  {
    id: "mm-1",
    category: "Marketing & Marke",
    text: "Wir haben eine klare Markenidentität und kommunizieren sie konsequent.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "mm-2",
    category: "Marketing & Marke",
    text: "Unsere Zielgruppe ist klar definiert und verstanden.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "mm-3",
    category: "Marketing & Marke",
    text: "Wir generieren kontinuierlich qualifizierte Leads über verschiedene Kanäle.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "mm-4",
    category: "Marketing & Marke",
    text: "Unser Marketing ist messbar und ROI-orientiert aufgebaut.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "mm-5",
    category: "Marketing & Marke",
    text: "Wir haben eine durchdachte Content- und Social-Media-Strategie.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "mm-6",
    category: "Marketing & Marke",
    text: "Unsere Website und Online-Präsenz repräsentieren unseren Wert professionell.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "mm-7",
    category: "Marketing & Marke",
    text: "Wir nutzen Kundenbewertungen und Referenzen aktiv für unser Marketing.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "mm-8",
    category: "Marketing & Marke",
    text: "Unser Marketing-Budget ist strategisch geplant, nicht zufällig verteilt.",
    type: "scale",
    scaleMin: 1,
    scaleMax: 10,
    scaleLabels: { min: "Trifft gar nicht zu", max: "Trifft voll zu" },
  },
  {
    id: "mm-text-1",
    category: "Marketing & Marke",
    text: "Wie unterscheidet sich Ihre Marke vom Wettbewerb?",
    type: "freetext",
    placeholder: "Beschreiben Sie Ihr Alleinstellungsmerkmal...",
  },
  {
    id: "mm-text-2",
    category: "Marketing & Marke",
    text: "Welcher Marketing-Kanal funktioniert bei Ihnen am besten und warum?",
    type: "freetext",
    placeholder: "z.B. Empfehlungen, Google Ads, Social Media, Events...",
  },
]

export const categories = [
  "Unternehmerisches Denken",
  "Leadership & Führung + Emotionen",
  "Vertrieb & Wachstum",
  "Selbstmanagement & Resilienz",
  "Finanzen & Controlling",
  "Marketing & Marke",
]
